### ISSUE TITLE
Wondering.

### ISSUE THREAD

**Issue by internpoon** [eleazargan/ama#3]
So, how do u determine the fastest server aka the best server ?

**Comment by eleazargan** [comment]
`The server has transformed how small businesses operate, and with falling costs and improving efficiency, there has never been a better time to start using a server in your business – but which one should you choose?`

`With a number of server varieties to choose from, it can be a daunting task understanding your options and then making the right choice. Should you have an onsite server? Will a cloud-based server offer the best service for your business? And how can virtualisation make your server choice even more flexible?`
